language: python
matrix:
  include:
  - python: 3.6
    env: TOXENV=py36
  - python: 3.7
    env: TOXENV=py37
  - python: 3.8
    env: TOXENV=py38
  - python: 3.9
    env: TOXENV=py39
  - python: 3.6
    env: TOXENV=py3pep8
  - python: 3.6
    env: TOXENV=docs
before_install:
- pip install codecov tox
script:
- tox
after_success:
- codecov -e TOXENV
deploy:
  provider: pypi
  username: __token__
  password:
    secure: ${{ secrets.PYPI_TOKEN }}
#      secure: EnafDF7ao7cagOJCsf+8SS7gQXdncUTz3bJ/aexXek4IBLa5oy/BWFa51SXDKEU4LMcOUafFpgIgXWGevHQWaTWpUqrbpovHHpyN/F2r56NbrMBR1oHyNG9xEd4hKMCwILtfH/ma0Vgt2Yj6DwnHLPlCv2e8kpHJ7nYiBy/2Juz2w82Ijx6tz/gr82kt/8+xG619bIpnUWR/Hv4OgFR5hs0cTENk7qdiWX0F+FNg+L/Ul9h0eMjcvh8CnT/5jIVWJu6OIgw/Dg6OhOzcuIqC/HP0Z5QiFOPf0Tr/iYT/nh9dWxvky8LFAo+PX8sdAhcu2EngolaU6ogUkzzdK5w2iP8UI3Efod92z7/YwE3qlOMfuqNOxUelPAupuIWmR8Tc/XStrcCgoqmhN7NdRS32o8WB1CXlzMdNx0u93uMaEd7mcbJ4hLAhNDQppiJ3MUwYWRVSAENjR6ysadTDkDPqcEdb9/4UfXZsCEWoeRCjwRyVD1rUgKnbcbRi2hUCFIFbYpUDwSziH630mcyJPrZqMl+agkLQ5venuTcYEHG1K6AmaGQBou6u1+LyExZHDUs/4PjaIOkDNzNgdvyWhcg1nRMjDb/ub863t9USi41uY2aUmIGeYVgkZWym2JDRScVsFQ+pJW4x76gbPs7h2SC9okcLA0Lst9AS7ddDjqnacKM=
  skip_existing: true
  distributions: sdist bdist_wheel
  server: https://test.pypi.org/legacy/
  on:
    all_branches: true
#    tags: true
    condition: $TOXENV == py36

